package com.xworkz.java;

import java.util.Collection;
import java.util.LinkedList;

import javax.swing.text.html.HTMLDocument.Iterator;

public class ArrayListWithNext {

	public static void main(String[] args) {

		String festival1 = "Ambedkar Jayanti";
		String festival2 = "Army Day";
		String festival3 = "Ahoi";
		String festival4 = "Arbaeen";
		String festival5 = "Auda pooja";
		String festival6 = "Anant Chaturdashi";
		String festival7 = "Dasara";
		String festival8 = " Boori Boot";
		String festival9 = "Reh";
		String festival10 = "Myoko";
		String festival11 = "Dree";
		String festival12 = "Pongtu";
		String festival13 = "Losar";
		String festival14 = "Murung";
		String festival15 = "Solang";
		String festival16 = "Mopin";
		String festival17 = "Monpa festival";
		String festival18 = "Dasara";
		String festival19 = "Deccan ";
		String festival20 = "Brahmotsavam";
		String festival21 = "Ambubachi";
		String festival22 = "Bhogali ";
		String festival23 = "Baishagu";
		String festival24 = "Dehing ";
		String festival25 = "Chhath ";
		String festival26 = "Bihula";
		String festival27 = "Maghi ";
		String festival28 = "Bastar ";
		String festival29 = "Ram Navmi";
		String festival30 = "Ganga Mahotsav";
		String festival31 = "Navaratri";
		String festival32 = "Khichdi";
		String festival33 = "Ganga Dussehra";
		String festival34 = "Kharchi Puja";
		String festival35 = "Hornbill festival";
		String festival36 = " Moatsu Festival";
		String festival37 = "Chapcharkut ";
		String festival38 = "Yaoshang";
		String festival39 = "Ganesh ";
		String festival40 = "Lok-rang Utsav";
		String festival53 = "Ladain";
		String festival54 = "Mando";
		String festival55 = "Rakhadumni";
		String festival56 = "Baisakhi";
		String festival57 = "Onam";
		String festival58 = "Yaoshang";
		String festival59 = "Chapcharkut ";
		String festival60 = "Akshaya Tritiya";

		Collection<String> collection = new LinkedList<String>();

		collection.add("theertha");
		collection.add("sharada pooja");
		collection.add("Khujaraho festival");
		collection.add("onam");
		collection.add("yaoshang");
		collection.add("chapcharkut");
		collection.add("baisakhi");
		collection.add("rakhadumni");
		collection.add("mando");
		collection.add("ladain");
		collection.add("sumburn");
		collection.add("ganpati");
		collection.add("raksha bandhan");
		collection.add("holi");
		collection.add("kutch");
		collection.add("bastar");
		collection.add("suburn");
		collection.add("mumbai");
		collection.add("dol");
		collection.add("bakri id");
		collection.add(festival60);
		collection.add(festival1);
		collection.add(festival2);
		collection.add(festival3);
		collection.add(festival4);
		collection.add(festival5);
		collection.add(festival6);
		collection.add(festival7);
		collection.add(festival8);
		collection.add(festival9);
		collection.add(festival10);
		collection.add(festival11);
		collection.add(festival12);
		collection.add(festival14);
		collection.add(festival13);
		collection.add(festival15);
		collection.add(festival16);
		collection.add(festival17);
		collection.add(festival18);
		collection.add(festival19);
		collection.add(festival20);
		collection.add(festival21);
		collection.add(festival22);
		collection.add(festival23);
		collection.add(festival24);
		collection.add(festival25);
		collection.add(festival26);
		collection.add(festival27);
		collection.add(festival28);
		collection.add(festival29);
		collection.add(festival31);
		collection.add(festival32);
		collection.add(festival33);
		collection.add(festival34);
		collection.add(festival35);
		collection.add(festival36);
		collection.add(festival37);
		collection.add(festival38);
		collection.add(festival39);
		collection.add(festival40);
		System.out.println(collection.isEmpty());
		System.out.println("number of festival:" + collection.size());
		java.util.Iterator<String> irt = collection.iterator();

		while (irt.hasNext()) {
			System.out.println(irt.next());
		}
		collection.remove(festival9);
		System.out.println(collection.contains("onam"));
		System.out.println("number of festival:" + collection.size());
		System.out.println("`````````````````````````````````");

		Collection<String> collection2 = new LinkedList<String>();

		collection2.add("Sachiin Joshi");
		collection2.add("Hrithik Roshan");
		collection2.add("Vicky Kaushal");
		collection2.add("Salman Khan");
		collection2.add("Vir Das");
		collection2.add("Tiger Shroff");
		collection2.add("Sushant Singh Rajput");
		collection2.add("Arjun Kapoor");
		collection2.add(" Shah Rukh Khan");
		collection2.add("Keanu Reeves");
		collection2.add("Keanu Reeves");
		collection2.add("Keanu Reeves");
		collection2.add("Aleksandër Moisiu ");
		collection2.add("Pjetër Gjoka ");
		collection2.add("Aaditi Pohankar");
		collection2.add("Ahsaas Chann");
		collection2.add("Ahaana Krishna");
		collection2.add("Advani Lakshmi Devi");
		collection2.add("Aditi Sarangdhar");
		collection2.add("Aditi Rao Hydar");
		collection2.add("Aditi Govitrikar");
		collection2.add("Aditi Sharma");
		collection2.add("Aditi Ravi");
		collection2.add("Aditi Arya");
		collection2.add("Adah Sharma");
		collection2.add("Abhirami");
		collection2.add("Aashka Goradia");
		collection2.add("Aarti Chhabria");
		collection2.add("Aarti Agarwal");
		collection2.add("Aarathi");
		collection2.add("Aanchal Munjal");
		collection2.add("Aamna Sharif");
		collection2.add("Aakanksha Singh");
		collection2.add("Aahana Kumra");
		collection2.add("Aisha Sharma");
		collection2.add("Amoolya");
		collection2.add("Ameesha Patel");
		collection2.add("Ameeta");
		collection2.add("Ambika");
		collection2.add("Amala Paul");
		collection2.add("Amala");
		collection2.add("Alaya Furniturewala");
		collection2.add("Alia Bhatt");
		collection2.add("Akshara Menon");
		collection2.add("Akshara Haasan");
		collection2.add("Akshara Gowda");
		collection2.add("Aksha Pardasany");
		collection2.add("Akanksha Juneja");
		collection2.add("Aishwarya Sakhuja");
		collection2.add("Aishwarya Rajesh");
		collection2.add("Aishwarya Rai Bachchan");
		collection2.add("Aishwarya Nag");
		collection2.add("Aishwarya Devan");
		collection2.add("Aishwarya Arjun");
		collection2.add("Aishwarya");
		collection2.add("Aishwarya");
		System.out.println("number of actors:" + collection.size());
		
		java.util.Iterator<String> irt10 = collection2.iterator();

		while (irt10.hasNext()) {
			System.out.println(irt10.next());
		}
		collection2.remove("Aishwarya");
		System.out.println(collection2.contains("khasi"));
		System.out.println("number of actors:" + collection2.size());
		System.out.println("`````````````````````````````````");

		Collection<String> collection3 = new LinkedList<String>();

		collection3.add("Hindi");
		collection3.add("english");
		collection3.add("marathi");
		collection3.add("kanada");
		collection3.add("tamil");
		collection3.add("uddu");
		collection3.add("Bengali");
		collection3.add("Gujarati");
		collection3.add("Bhojpuri");
		collection3.add("Malayalam");
		collection3.add("Odia");
		collection3.add("Punjabi");
		collection3.add("Rajasthani");
		collection3.add("Chhattisgarhi");
		collection3.add("Assamese");
		collection3.add("Maithili");
		collection3.add("Haryanvi");
		collection3.add("Khotta");
		collection3.add("Marwari");
		collection3.add("Santali");
		collection3.add("Kashmiri");
		collection3.add("khandi");
		collection3.add("Malvi");
		collection3.add("Sadri");
		collection3.add("Mewari");
		collection3.add("Wagdi");
		collection3.add("Lambadi");
		collection3.add("Bhilodi");
		collection3.add("Harauti");
		collection3.add("Nepali");
		collection3.add("Gondi");
		collection3.add("Baghel Khandi");
		collection3.add("Sambalpuri");
		collection3.add("Dogri");
		collection3.add("Garhwali");
		collection3.add("Nimadi");
		collection3.add("Surjapuri");
		collection3.add("Konkani");
		collection3.add("Kumauni");
		collection3.add("Oraon");
		collection3.add("Tulu");
		collection3.add("Manipuri");
		collection3.add("Surgujia");
		collection3.add("Sindhi");
		collection3.add("Bagri");
		collection3.add("Ahirani");
		collection3.add("Banjari");
		collection3.add("Brajbhasha");
		collection3.add("Dhundhari");
		collection3.add("Boro");
		collection3.add("Ho");
		collection3.add("Gujar");
		collection3.add("Mundari");
		collection3.add("Garo");
		collection3.add("Kangri");
		collection3.add("Kachchhi");
		collection3.add("Khasi");
		collection3.add("mara");
		collection3.add("nidi");
		collection3.add("sindu");
		System.out.println("number of language:" + collection3.size());
		java.util.Iterator<String> irt1 = collection3.iterator();

		while (irt1.hasNext()) {
			System.out.println(irt1.next());
		}
		System.out.println("````````````````````````````");
		collection3.remove("mara");
		System.out.println(collection3.contains("khasi"));
		System.out.println("number of language:" + collection3.size());
		System.out.println("`````````````````````````````````");

		Collection<String> collection4 = new LinkedList<String>();

		collection4.add("Bad Boys for Life");
		collection4.add("Sonic the Hedgehog");
		collection4.add("Tenet");
		collection4.add("Dolittle");
		collection4.add("Birds of Prey");
		collection4.add("The Invisible Man");
		collection4.add("The Gentlemen");
		collection4.add("The Call of the Wild");
		collection4.add("Onward");
		collection4.add("Mulan");
		collection4.add("tanhaji");
		collection4.add("Tolo Tolo");
		collection4.add("The Grudge");
		collection4.add("Fantasy Island");
		collection4.add("Underwater");
		collection4.add("The New Mutants");
		collection4.add("Unhinged");
		collection4.add("Like a Boss");
		collection4.add("Bloodshot");
		collection4.add("Emma");
		collection4.add("Trolls World Tour");
		collection4.add("Gretel & Hansel");
		collection4.add("Scoob!");
		collection4.add("Brahms: The Boy II");
		collection4.add("The Turning");
		collection4.add("The Way Back");
		collection4.add("La Belle Epoque");
		collection4.add("I Still Believe");
		collection4.add("The Hunt");
		collection4.add("Las Pildoras De Mi Novio");
		collection4.add("Mission: Impossible 2 ");
		collection4.add("Gladiator");
		collection4.add("Cast Away");
		collection4.add("What Women Want");
		collection4.add("Dinosaur");
		collection4.add("How the Grinch Stole Christmas");
		collection4.add("Meet the Parents");
		collection4.add("The Perfect Storm");
		collection4.add("X-Men");
		collection4.add("What Lies Beneath");
		collection4.add("Avengers: Endgame");
		collection4.add("Star Wars: The Force Awakens");
		collection4.add("Avengers: Infinity War");
		collection4.add("Jurassic World");
		collection4.add("The Lion King");
		collection4.add("The Avengers");
		collection4.add("Furious 7");
		collection4.add("Frozen II");
		collection4.add("Avengers: Age of Ultron");
		collection4.add("Black Panther");
		collection4.add("Harry Potter and the Deathly Hallows – Part 2");
		collection4.add("Star Wars: The Last Jedi");
		collection4.add("Jurassic World: Fallen Kingdom");
		collection4.add("Frozen");
		collection4.add("Beauty and the Beast");
		collection4.add("Incredibles 2");
		collection4.add("The Fate of the Furious");
		collection4.add("Iron Man 3");
		collection4.add("gita govida");
		collection4.add("comrade");
		System.out.println("number of movies:" + collection4.size());
		java.util.Iterator<String> irt2 = collection4.iterator();

		while (irt2.hasNext()) {
			System.out.println(irt2.next());
		}
		collection4.remove("Incredibles 2");
		System.out.println(collection.contains("onam"));
		System.out.println("number of movies:" + collection4.size());;
		System.out.println("``````````````````````````````````````````");

		Collection<String> collection5 = new LinkedList<String>();
		collection5.add("Capitol Hill");
		collection5.add("Crash Course");
		collection5.add("Copy & Pastry");
		collection5.add("Consolevania");
		collection5.add("Compulsions");
		collection5.add("Community ");
		collection5.add("Coming Out");
		collection5.add("Comedians in Cars Getting Coffee");
		collection5.add("CollegeHumor");
		collection5.add("Codefellas");
		collection5.add("Class of 2017");
		collection5.add("Clutch");
		collection5.add("Classic Alice");
		collection5.add("Clark and Michael");
		collection5.add("Chop Socky Boom");
		collection5.add("Childrens Hospital");
		collection5.add("Chelsea Does");
		collection5.add("Chelsea");
		collection5.add("Chateau Laurier");
		collection5.add("Chance");
		collection5.add("Chad Vader");
		collection5.add("CELL");
		collection5.add("Castlevania");
		collection5.add("Carpool Karaoke");
		collection5.add("Carmilla");
		collection5.add("Titans Season 3");
		collection5.add("Inside Edge Season 3");
		collection5.add("Lost in Space Season 3");
		collection5.add("Hiccups & Hookups");
		collection5.add("Hawkeye");
		collection5.add("Cowboy Bebop Season 1");
		collection5.add("The Wheel of Time");
		collection5.add("Star Trek: Discovery Season 4");
		collection5.add("Special Ops 1.5");
		collection5.add("Call My Agent: Bollywood");
		collection5.add("Little Things Season 4");
		collection5.add("Succession Season 3");
		collection5.add("House of Secrets: The Burari");
		collection5.add("Break Point");
		collection5.add("Foundation Season 1");
		collection5.add("Kota Factory Season 2");
		collection5.add("Star Wars: Visions Season 1");
		collection5.add("Squid Game Season 1");
		collection5.add("The Last Man Season 1");
		collection5.add("Mumbai Diaries 26/11");
		collection5.add("Money Heist Season 5");
		collection5.add("The Empire Season 1");
		collection5.add("What If…? Season 1");
		collection5.add("Feels Like Ishq Season 1");
		collection5.add("Ted Lasso Season 2");
		collection5.add("Never Have I Ever Season 2");
		collection5.add("Ray Season 1");
		collection5.add("Loki Season 1");
		collection5.add("The Family Man Season 2");
		collection5.add("kimit su yaiba");
		collection5.add("attack of taitan");
		collection5.add("lost in space");
		collection5.add("charnobly");
		collection5.add("dark");
		collection5.add("streger things");
		System.out.println("number of web series:" + collection5.size());
		java.util.Iterator<String> irt3 = collection5.iterator();

		while (irt3.hasNext()) {
			System.out.println(irt3.next());
		}
		collection5.remove("dark");
		System.out.println(collection.contains("dark"));
		System.out.println("number of we series:" + collection5.size());;
		System.out.println("``````````````````````````````````````````");
		
		System.out.println("```````````````````````````````````````");

		Collection<String> collection6 = new LinkedList<String>();

		collection6.add("aurangabad");
		collection6.add("amalner");
		collection6.add("pune");
		collection6.add("jalna");
		collection6.add("ajintha");
		collection6.add("paithan");
		collection6.add("maysor");
		collection6.add("bangloare");
		collection6.add("dilhi");
		collection6.add("kolkatta");
		collection6.add("paris");
		collection6.add("punjab");
		collection6.add("amritsur");
		collection6.add("jaypur");
		collection6.add("nashik");
		collection6.add("patayya");
		collection6.add("goa");
		collection6.add("huballi");
		collection6.add("kannad");
		collection6.add("dhule");
		collection6.add("40 gav");
		collection6.add("raj kot");
		collection6.add("ahmdabad");
		collection6.add("gandhi nagar");
		collection6.add("surat");
		collection6.add("mumbai");
		collection6.add("rajpal");
		collection6.add("bhuneshwar");
		collection6.add("manglore");
		collection6.add("abu dabi");
		collection6.add("kolhapur");
		collection6.add("ichalkaranji");
		collection6.add("sangli");
		collection6.add("miraj");
		collection6.add("dharwad");
		collection6.add("shiratwad");
		collection6.add("nipani");
		collection6.add("chikurdi");
		collection6.add("ghokag");
		collection6.add("jamakahand");
		collection6.add("shirdi");
		collection6.add("gangapur");
		collection6.add("bhosawal");
		collection6.add("shirpur");
		collection6.add("airandol");
		collection6.add("jalgav");
		collection6.add("fagne");
		collection6.add("mannad");
		collection6.add("parbhani");
		collection6.add("latur");
		collection6.add("agra");
		collection6.add("ranchi");
		collection6.add("chiru");
		collection6.add("nepal");
		collection6.add("kolhar");
		collection6.add("kur");
		collection6.add("madkiri");
		collection6.add("virajpet");
		collection6.add("ooty");
		collection6.add("mandya");
		System.out.println("number of city name:" + collection6.size());
		java.util.Iterator<String> irt4 = collection6.iterator();

		while (irt4.hasNext()) {
			System.out.println(irt4.next());
		}
		collection6.remove("virajpet");
		System.out.println(collection6.contains("madikeri")+ "contains");
		System.out.println("number of city name:" + collection6.size());;
		System.out.println("``````````````````````````````````````````");
		System.out.println("````````````````````````````````````````");

		Collection<String> collection7 = new LinkedList<String>();

		collection7.add("Arisa Pitha");
		collection7.add("Apple Halwa");
		collection7.add("Balushahi");
		collection7.add("Boondi");
		collection7.add("Gajar ka halwa");
		collection7.add("Ghevar");
		collection7.add("Gulab jamun");
		collection7.add("Imarti");
		collection7.add("Jalebi");
		collection7.add("Kaju katli");
		collection7.add("Kalakand");
		collection7.add("Kheer");
		collection7.add("Khirmohan");
		collection7.add("Kulfi");
		collection7.add("Laddu");
		collection7.add("Lassi");
		collection7.add("Motichoor laddu");
		collection7.add("Malpua");
		collection7.add("Nankhatai");
		collection7.add("Petha");
		collection7.add("Phirni");
		collection7.add("Rabri");
		collection7.add("Sheera");
		collection7.add("Singori");
		collection7.add("Sohan halwa");
		collection7.add("Sohan papdi, pateesa");
		collection7.add("Amriti");
		collection7.add("Cham cham");
		collection7.add("Chandrapuli");
		collection7.add("Chhena gaja");
		collection7.add("Chhena jalebi");
		collection7.add("Chhena Jhili");
		collection7.add("Chhena kheeri");
		collection7.add("Chhena poda");
		collection7.add("Chuda Ghasa");
		collection7.add("Coconut Barfi");
		collection7.add("Kheer sagar");
		collection7.add("Ledikeni");
		collection7.add("Lyangcha");
		collection7.add("Malapua");
		collection7.add("Mihidana");
		collection7.add("Misti doi");
		collection7.add("Pantua");
		collection7.add("Pithe");
		collection7.add("Puri Khaja");
		collection7.add("Rabri	");
		collection7.add("Rasabali");
		collection7.add("Ras malai");
		collection7.add("Rasgulla");
		collection7.add("Sandesh");
		collection7.add("Sirir naru");
		collection7.add("Ada");
		collection7.add("Adhirasam");
		collection7.add("Bandar laddu");
		collection7.add("Chikki");
		collection7.add("Dharwad Pedha");
		collection7.add("Double ka Meetha");
		collection7.add("god pole");
		collection7.add("god bhat");
		collection7.add("fafad");
		System.out.println("number of sweets:" + collection7.size());
		java.util.Iterator<String> irt5 = collection7.iterator();

		while (irt5.hasNext()) {
			System.out.println(irt5.next());
		}
		collection7.remove("Incredi");
		System.out.println(collection7.contains("fafad")+ "contains");
		System.out.println("number of sweets:" + collection7.size());;
		System.out.println("``````````````````````````````````````````");
		System.out.println("````````````````````````````````````");

		Collection<String> collection8 = new LinkedList<String>();

		collection8.add("Royal Enfield Classic 350");
		collection8.add("TVS Jupiter 125");
		collection8.add("TVS Apache RTR 160");
		collection8.add("Yamaha YZF R15 V3");
		collection8.add("TVS Apache RTR 160 4V");
		collection8.add("Yamaha MT 15");
		collection8.add("TVS Sport");
		collection8.add("Hero Splendor Plus");
		collection8.add("TVS Jupiter");
		collection8.add("TVS XL100");
		collection8.add("TVS Apache RTR 200 4V");
		collection8.add("TVS Apache RR 310");
		collection8.add("TVS Scooty Pep Plus");
		collection8.add("TVS Apache RTR 180");
		collection8.add("TVS Star City Plus");
		collection8.add("TVS Scooty Zest");
		collection8.add("TVS NTORQ 125");
		collection8.add("TVS Radeon");
		collection8.add("TVS iQube Electric");
		collection8.add("TVS Raider");
		collection8.add("Yamaha YZF R15 V3");
		collection8.add("TVS Apache RTR 160");
		collection8.add("Jawa 42");
		collection8.add("Jawa Perak");
		collection8.add("Jawa");
		collection8.add("Jawa Cruiser");
		collection8.add("Bajaj Pulsar 150");
		collection8.add("Bajaj Pulsar NS200");
		collection8.add("Bajaj Pulsar 220 F");
		collection8.add("Bajaj Pulsar RS200");
		collection8.add("Bajaj Pulsar 125 Neon");
		collection8.add("Bajaj CT100");
		collection8.add("Bajaj Dominar 400");
		collection8.add("Bajaj Pulsar NS 125");
		collection8.add("Bajaj Pulsar NS160");
		collection8.add("Bajaj Platina 100");
		collection8.add("Bajaj Pulsar F250	");
		collection8.add("Bajaj Pulsar 180	");
		collection8.add("Bajaj Chetak");
		collection8.add("Bajaj CT110");
		collection8.add("Bajaj Dominar 250");
		collection8.add("Bajaj Avenger Cruise 220");
		collection8.add("Bajaj Pulsar N250");
		collection8.add("Bajaj Platina 110 H Gear");
		collection8.add("Bajaj Avenger Street 160");
		collection8.add("Bajaj Platina 110");
		collection8.add("Bajaj NS250");
		collection8.add("Bajaj Avenger 400");
		collection8.add("KTM RC 200");
		collection8.add("KTM 200 Duke");
		collection8.add("KTM 125 Duke");
		collection8.add("KTM RC 390");
		collection8.add("KTM 390 Duke");
		collection8.add("KTM 250 Duke");
		collection8.add("KTM RC 125 ");
		collection8.add("2021 KTM RC 125");
		collection8.add("2021 KTM RC 200");
		collection8.add("KTM 390 Adventure");
		collection8.add("pulsar 150");
		collection8.add("KTM 250 Adventure");
		System.out.println("number of bike:" + collection8.size());
		java.util.Iterator<String> irt6 = collection8.iterator();

		while (irt6.hasNext()) {
			System.out.println(irt6.next());

		}
		collection8.remove("pulsar 150");
		System.out.println(collection8.contains("ktm")+ "contains");
		System.out.println("number of bikes:" + collection8.size());;
		System.out.println("``````````````````````````````````````````");
		System.out.println("``````````````````````````````````");

		Collection<String> collection9 = new LinkedList<String>();
		collection9.add("Aston Martin Cygnet Hatchback ");
		collection9.add("Aston Martin DB11 Coupe 2016");
		collection9.add("Aston Martin DB11 Coupe 2017");
		collection9.add("Aston Martin DB11 Coupe ");
		collection9.add("Aston Martin DBS Volante Conv");
		collection9.add("Aston Martin DB9 Coupe 2016");
		collection9.add("Aston Martin DB11 Volante Con");
		collection9.add("Aston Martin DB11 Volante Con");
		collection9.add("Acura ILX Premium Sedan 2019");
		collection9.add("Audi A1 Ambition Hatchback 201");
		collection9.add("Audi A1 Sportback Hatchback 2015");
		collection9.add("Audi A1 Sportback S Line Hatchback 2019");
		collection9.add("Audi A1 Sport Hatchback 2016");
		collection9.add("Audi A3 Ambition Convertible 201");
		collection9.add("Audi A3 Ambition Hatchback 2014");
		collection9.add("Audi A3 Attraction Convertible 2014");
		collection9.add("Audi A3 E-Tron Premium Plus H");
		collection9.add("Audi A3 E-Tron Ambiente Hybrid...");
		collection9.add("audi A1");
		collection9.add("Audi A2");
		collection9.add("Audi A3");
		collection9.add("Audi A4");
		collection9.add("Audi A5");
		collection9.add("Audi A6");
		collection9.add("Audi 255d");
		collection9.add("Audi 450d");
		collection9.add("Audi 220d");
		collection9.add("Audi 250d");
		collection9.add("Jaguar E-Pace R Dynamic HSE SUV 2021");
		collection9.add("Jaguar E-Pace R-Dynamic S SU");
		collection9.add("Jaguar E-Pace R-Dynamic S SUV 2019");
		collection9.add("Jaguar E-Pace R Dynamic SUV");
		collection9.add("Jaguar F-Pace Prestige SUV 20");
		collection9.add("Jaguar F Pace Prestige SUV 2020");
		collection9.add("Jaguar F-Pace R-Sport SUV 2018");
		collection9.add("Jaguar F-Pace S SUV 2021");
		collection9.add("Jaguar F-Type Convertible 2017");
		collection9.add("Jaguar F-Type Base Convertible 2017");
		collection9.add("Jaguar F-Type Convertible 2018");
		collection9.add("Jaguar F-Type Convertible 2020");
		collection9.add("Jaguar F-Type R Coupe 2020");
		collection9.add("Jaguar F-Type Convertible 2021");
		collection9.add("Jaguar F-Type R Dynamic Convertible 2018");
		collection9.add("Jaguar F-Type R Dynamic Coupe 2019");
		collection9.add("Mercedes AMG GT AMG GT Roadster 2018");
		collection9.add("Mercedes-Benz A-Class 200 Sedan 2019");
		collection9.add("Mercedes-Benz A-Class 220 Sedan 2019");
		collection9.add("Mercedes-Benz A-Class A160...");
		collection9.add("Mercedes-Benz A Class Hatchback 2019");
		collection9.add("Mercedes-Benz AMG GT C Coupe 2020");
		collection9.add("Mercedes-Benz AMG GT Coupe 2020");
		collection9.add("Mercedes-Benz AMG GT Coupe 2017");
		collection9.add("Mercedes-Benz AMG GT Roadster 2019");
		collection9.add("Mercedes-Benz B-Class B200 Sport Mini...");
		collection9.add("Mercedes-Benz B-Class Electric Drive...");
		collection9.add("Mercedes-Benz B Class Hatchback 2018");
		collection9.add("Mercedes-Benz C-Class AMG C43 Coupe 2017");
		collection9.add("Volvo C30 Hatchback 2008");
		collection9.add("Volvo S60 Cross Country Summum Sedan...");
		collection9.add("Volvo S60 R Design Sedan 2019");
		collection9.add("Volvo S60 R-Design Sedan 2019");
		collection9.add("Volvo S60 Recharge Polestar Sedan 2021");
		collection9.add("Volvo S60 Summum Sedan 2014");
		collection9.add("Volvo S60 T5 Sedan 2018");
		collection9.add("Volvo S90 Inscription PHEV Sedan 2019");
		System.out.println("number of cars :" + collection9.size());
		java.util.Iterator<String> irt7 = collection9.iterator();

		while (irt7.hasNext()) {
			System.out.println(irt7.next());
		}
		collection9.remove("Audi A3");
		System.out.println(collection9.contains("Audi A4")+ "contains");
		System.out.println("number of cars:" + collection9.size());;
		System.out.println("``````````````````````````````````````````");

		Collection<String> collection10 = new LinkedList<String>();
		collection10.add("Brown Suga Babe ");
		collection10.add("Lip Gloss");
		collection10.add("Zolani K");
		collection10.add("Satin");
		collection10.add("Creamy");
		collection10.add("Matte");
		collection10.add("Lip Stains or Tints");
		collection10.add("Glossy");
		collection10.add("metallic");
		collection10.add("Tinted Lip Balm");
		collection10.add("Lip Liner");
		collection10.add("Cream Lipsticks");
		collection10.add("Gloss Lipsticks");
		collection10.add("Lipstick Stains");
		collection10.add("Long-Wearing");
		collection10.add("Matte Lipsticks");
		collection10.add("Moisturizing Lipsticks");
		collection10.add("Pearl/Frosted Lipsticks");
		collection10.add("Sheer/Satin Lipsticks");
		collection10.add("Black Honey");
		collection10.add(" Lip Pencil");
		collection10.add("NARS Semi Matte");
		collection10.add("Chanel Rouge Allure ");
		collection10.add("MAC Red Lipstick");
		collection10.add("Revlon Super Lustrous ");
		collection10.add("Tom Ford Lip Color");
		collection10.add("NARS Lipstick");
		collection10.add("GIORGIO ARMANI BEAUTY Rouge");
		collection10.add("Brown by Bobbi Brown");
		collection10.add("Longwear Fluid Lip Color");
		collection10.add("CHARLOTTE TILBURY");
		collection10.add("DIOR Rouge Dior Lipstick");
		collection10.add("M.A.C Lipstick Matte");
		collection10.add("SEPHORA COLLECTION Cream Lip ");
		collection10.add("Exaltée by Chanel");
		collection10.add("Rimmel London Lip Stick");
		collection10.add("DIOR Rouge Dior Lipstick");
		collection10.add("M.A.C Viva Glam Lipstick");
		collection10.add("Tom Ford Lip Color");
		collection10.add("Lancome ROUGE IN LOVE");
		collection10.add("Tom Ford Lip Color");
		collection10.add("L’Oréal Paris Colour Riche Lipstick");
		collection10.add("Rimmel London Lasting Finish");
		collection10.add("Kate Lipstick");
		collection10.add("Maybelline Color ");
		collection10.add("Covergirl Lip Perfection Lipstick");
		collection10.add("New Nudes Sheer Gel Lipstick");
		collection10.add("ESTÉE LAUDER Pure Color Envy Sculpting Lipstick");
		collection10.add("Shiseido Lipstick");
		collection10.add("LIPSTICK QUEEN Medieval Lipstick");
		collection10.add("CONVERTIBLE COLOR");
		collection10.add("SHINE FEVER ");
		collection10.add("Ruby Woo by M.A.C.");
		collection10.add("Black Honey Almost Lipstick");
		collection10.add("M.A.C Lip Penci");
		collection10.add("Lady Danger by M.A.C.");
		collection10.add("Pirate by Chanel");
		collection10.add("Schiap by NARS");
		collection10.add("Spice by M.A.C.");
		collection10.add("red");

		System.out.println("number of lipstick:" + collection10.size());
		java.util.Iterator<String> irt8 = collection10.iterator();

		while (irt8.hasNext()) {
			System.out.println(irt8.next());
		}
		collection10.remove("red");
		System.out.println(collection10.contains("kate Lipstick")+ " contains");
		System.out.println("number of lipstick:" + collection10.size());;
		System.out.println("``````````````````````````````````````````");

	}

}
